[project]
name = "maturin"
requires-python = ">=3.7"

dependencies = ["tomli>=1.1.0 ; python_version<'3.11'"]

[build-system]
requires = ["setuptools", "wheel>=0.36.2", "tomli>=1.1.0 ; python_version<'3.11'", "setuptools-rust>=1.4.0"]
build-backend = "setuptools.build_meta"